# Generated by Django 4.0.3 on 2022-03-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='info', verbose_name='Фото')),
                ('url', models.URLField(default='', verbose_name='Ссылка')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.block')),
            ],
        ),
    ]
